export const Role = {
  appbuilder: 'appbuilder',
  h5builder: 'h5builder',
  audience: 'audience',
  scheduler: 'scheduler',
  h5builder_v2: 'h5builder_v2',
  retention: 'retention',
  dimension: 'dimension',
  publish: 'publish',
  power: 'power',
  importData: 'importData',
  management: '"management"',
  LPO: 'LPO',
  new_android_edit: 'new_android_edit',
  new_ios_edit: 'new_ios-edit',
  layer: 'layer',
  regexp_match: 'regexp_match',
  ai: 'ai',
  flagtyp: 'flagtyp' // 高级flag类型
};
